version: '3'

services:
    vue:
        build: .
        ports:
            - 8080:8080
            - 8000:8000
        volumes:
            - ./share:/app
        stdin_open: true
        tty: true
